apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "debug-toolbox.fullname" . }}
  labels:
    app: {{ template "debug-toolbox.fullname" . }}
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "The toolbox need write into volumes"
    ignore-check.kube-linter.io/run-as-non-root: "The toolbox needs to run as privileged because debugging purpose"
    ignore-check.kube-linter.io/drop-net-raw-capability: "Required for network debugging."
    ignore-check.kube-linter.io/privilege-escalation-container: "Privilege escalation needed for debugging."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "debug-toolbox.fullname" . }}
  template:
    metadata:
      name: {{ template "debug-toolbox.fullname" . }}
      labels:
        app: {{ template "debug-toolbox.fullname" . }}
      annotations:
        releasetime: {{ now | quote }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      hostIPC: {{ .Values.hostIPC }}
      hostPID: {{ .Values.hostPID }}
      priorityClassName: {{ .Values.priorityClassName }}
{{ include "debug-toolbox.nodeSelector" . | indent 6 }}
{{ include "debug-toolbox.affinity" . | indent 6 }}
{{ include "debug-toolbox.tolerations" . | indent 6 }}
      serviceAccountName: {{ template "debug-toolbox.fullname" . }}
      containers:
      - name: debug-toolbox
        image: {{ .Values.image.registry }}/{{ .Values.image.debugContainerImage.name }}:{{ .Values.image.debugContainerImage.tag }}
        command:
        - /bin/sh
        - -c
        - while true; do echo "I am ready" && sleep 30; done;
        securityContext:
{{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        - name: manifests-volume
          mountPath: /manifests
        - name: policies-volume
          mountPath: /policies
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- include "debug-toolbox.extraVolumeMounts" . | indent 8 }}
      volumes:
      - name: manifests-volume
        hostPath:
          path: /etc/kubernetes/manifests
      - name: policies-volume
        hostPath:
          path: /etc/kubernetes/policies
{{- include "debug-toolbox.extraVolumes" . | indent 6 }}
