apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "debug-toolbox.fullname" . }}
  labels:
    app: {{ template "debug-toolbox.fullname" . }}
spec:
  egress:
    - {}
  ingress:
    - {}
  podSelector:
    matchLabels:
      app: {{ template "debug-toolbox.fullname" . }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "debug-toolbox.fullname" . }}-dns
  labels:
    app: {{ template "debug-toolbox.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "debug-toolbox.fullname" . }}
  policyTypes:
    - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: UDP
      port: 1053